version: '3'
services:
  postgres:
    container_name: ads_postgres
    build:
      context: docker/postgres
      dockerfile: Dockerfile-postgres
    ports:
      - "25778:5432"

  nginx:
    container_name: ads_nginx
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - "./docker/nginx:/etc/nginx/conf.d/"
      - ".:/var/www/html"
    links:
      - php

  php:
    container_name: ads_php
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile-phpfpm
    volumes:
      - ".:/var/www/html:rw"
    links:
      - postgres
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
      USER_ID:
      IS_WINDOWS: